-- Dữ liệu dinh dưỡng tham khảo (Kcal trên 100g hoặc 100ml)
INSERT INTO ingredients (name, standard_unit, calories_per_unit, image) VALUES
-- 1. THỊT (MEATS)
('Ức gà (sống)', 'gram', 165, NULL),
('Đùi gà (bỏ da)', 'gram', 119, NULL),
('Cánh gà', 'gram', 203, NULL),
('Thịt bò (thăn)', 'gram', 250, NULL),
('Thịt bò (bắp)', 'gram', 201, NULL),
('Thịt bò xay (ít mỡ)', 'gram', 215, NULL),
('Thịt lợn (nạc thăn)', 'gram', 143, NULL),
('Thịt lợn (ba chỉ)', 'gram', 518, NULL),
('Sườn lợn', 'gram', 277, NULL),
('Thịt vịt', 'gram', 337, NULL),
('Thịt cừu', 'gram', 294, NULL),
('Thịt dê', 'gram', 143, NULL),
('Xúc xích', 'gram', 301, NULL),
('Thịt xông khói (Bacon)', 'gram', 541, NULL),
('Giò lụa', 'gram', 136, NULL),

-- 2. HẢI SẢN (SEAFOOD)
('Cá hồi', 'gram', 208, NULL),
('Cá ngừ', 'gram', 132, NULL),
('Cá thu', 'gram', 205, NULL),
('Cá rô phi', 'gram', 96, NULL),
('Cá trắm', 'gram', 91, NULL),
('Cá chép', 'gram', 127, NULL),
('Tôm tươi', 'gram', 99, NULL),
('Mực ống', 'gram', 92, NULL),
('Bạch tuộc', 'gram', 82, NULL),
('Cua biển', 'gram', 97, NULL),
('Ghẹ', 'gram', 84, NULL),
('Nao/Hàu', 'gram', 68, NULL),
('Sò điệp', 'gram', 111, NULL),
('Lươn', 'gram', 184, NULL),

-- 3. TRỨNG & SỮA (DAIRY & EGGS)
('Trứng gà', 'quả', 155, NULL), -- 155 kcal/100g (khoảng 2 quả)
('Trứng vịt', 'quả', 185, NULL),
('Trứng cút', 'quả', 158, NULL),
('Lòng trắng trứng', 'gram', 52, NULL),
('Sữa tươi không đường', 'ml', 42, NULL),
('Sữa tươi có đường', 'ml', 76, NULL),
('Sữa chua không đường', 'gram', 59, NULL),
('Sữa chua có đường', 'gram', 98, NULL),
('Phô mai (Cheddar)', 'gram', 402, NULL),
('Phô mai (Mozzarella)', 'gram', 280, NULL),
('Bơ lạt (Butter)', 'gram', 717, NULL),
('Sữa đặc', 'ml', 321, NULL),
('Whey Protein', 'gram', 370, NULL),

-- 4. TINH BỘT & NGŨ CỐC (STARCHES & GRAINS)
('Gạo trắng', 'gram', 130, NULL), -- Đã nấu
('Gạo lứt', 'gram', 110, NULL),   -- Đã nấu
('Yến mạch', 'gram', 389, NULL),  -- Sống
('Khoai lang', 'gram', 86, NULL),
('Khoai tây', 'gram', 77, NULL),
('Ngô (Bắp) ngọt', 'gram', 86, NULL),
('Bánh mì trắng', 'gram', 265, NULL),
('Bánh mì đen/nguyên cám', 'gram', 250, NULL),
('Bún tươi', 'gram', 110, NULL),
('Phở tươi', 'gram', 123, NULL),
('Miến dong', 'gram', 332, NULL), -- Khô
('Mì ý (Spaghetti)', 'gram', 158, NULL), -- Đã luộc
('Đậu xanh', 'gram', 347, NULL),
('Đậu đen', 'gram', 341, NULL),
('Đậu đỏ', 'gram', 329, NULL),
('Hạt quinoa (Diêm mạch)', 'gram', 120, NULL), -- Đã nấu

-- 5. RAU CỦ (VEGETABLES)
('Súp lơ xanh (Bông cải)', 'gram', 34, NULL),
('Súp lơ trắng', 'gram', 25, NULL),
('Cà rốt', 'gram', 41, NULL),
('Dưa chuột (Dưa leo)', 'gram', 15, NULL),
('Cà chua', 'gram', 18, NULL),
('Rau muống', 'gram', 19, NULL),
('Rau ngót', 'gram', 35, NULL),
('Rau cải ngọt', 'gram', 20, NULL),
('Cải bắp', 'gram', 25, NULL),
('Cải thảo', 'gram', 16, NULL),
('Xà lách', 'gram', 15, NULL),
('Rau chân vịt (Bina)', 'gram', 23, NULL),
('Bí đỏ', 'gram', 26, NULL),
('Bí xanh (Bí đao)', 'gram', 13, NULL),
('Mướp đắng (Khổ qua)', 'gram', 17, NULL),
('Su su', 'gram', 19, NULL),
('Hành tây', 'gram', 40, NULL),
('Ớt chuông', 'gram', 20, NULL),
('Đậu cô ve', 'gram', 31, NULL),
('Giá đỗ', 'gram', 30, NULL),
('Măng tây', 'gram', 20, NULL),
('Nấm hương', 'gram', 34, NULL),
('Nấm đùi gà', 'gram', 24, NULL),
('Nấm kim châm', 'gram', 37, NULL),

-- 6. TRÁI CÂY (FRUITS)
('Chuối', 'gram', 89, NULL),
('Táo', 'gram', 52, NULL),
('Cam', 'gram', 47, NULL),
('Quýt', 'gram', 53, NULL),
('Bưởi', 'gram', 38, NULL),
('Dưa hấu', 'gram', 30, NULL),
('Dưa lưới', 'gram', 34, NULL),
('Xoài chín', 'gram', 60, NULL),
('Dứa (Thơm)', 'gram', 50, NULL),
('Thanh long', 'gram', 60, NULL),
('Nho', 'gram', 67, NULL),
('Dâu tây', 'gram', 32, NULL),
('Bơ (Avocado)', 'gram', 160, NULL),
('Ổi', 'gram', 68, NULL),
('Đu đủ', 'gram', 43, NULL),
('Lê', 'gram', 57, NULL),
('Vải', 'gram', 66, NULL),
('Nhãn', 'gram', 60, NULL),
('Sầu riêng', 'gram', 147, NULL),

-- 7. CÁC LOẠI HẠT & DẦU (NUTS & OILS)
('Hạt điều', 'gram', 553, NULL),
('Hạt hạnh nhân', 'gram', 579, NULL),
('Hạt óc chó', 'gram', 654, NULL),
('Đậu phộng (Lạc)', 'gram', 567, NULL),
('Hạt chia', 'gram', 486, NULL),
('Dầu ô liu', 'ml', 884, NULL),
('Dầu thực vật (Dầu ăn)', 'ml', 884, NULL),
('Dầu dừa', 'ml', 862, NULL),
('Bơ đậu phộng', 'gram', 588, NULL),

-- 8. GIA VỊ & SỐT (CONDIMENTS)
('Muối', 'gram', 0, NULL),
('Đường trắng', 'gram', 387, NULL),
('Mật ong', 'ml', 304, NULL),
('Nước mắm', 'ml', 10, NULL), -- Xấp xỉ
('Xì dầu (Nước tương)', 'ml', 53, NULL),
('Tương ớt', 'gram', 90, NULL),
('Sốt Mayonnaise', 'gram', 680, NULL),
('Giấm', 'ml', 18, NULL),
('Tiêu đen', 'gram', 251, NULL),
('Tỏi', 'gram', 149, NULL),
('Hành tím', 'gram', 72, NULL),
('Gừng', 'gram', 80, NULL);