ALTER TABLE `exercises`
ADD COLUMN `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE `workoutplan`
ADD COLUMN `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE `menu`
ADD COLUMN `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE `challenges`
ADD COLUMN `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE `dishes`
ADD COLUMN `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE `meal`
ADD COLUMN `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE;